resource "random_pet" "my-pet" {
  prefix = "mr"
  separator = "."
  length = "1"
}

output "pet-name" {
  value = random_pet.my-pet.id
  description = "Pet name generated by the random_pet resource."
}